language: cpp

matrix:
  include:
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v3.16.63
      - KERNEL_VERSION=3.16.63-031663
      - KERNEL_VERSION_C=201902112033
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v3.18.136
      - KERNEL_VERSION=3.18.136-0318136
      - KERNEL_VERSION_C=201902230608
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v4.4.176
      - KERNEL_VERSION=4.4.176-0404176
      - KERNEL_VERSION_C=201902230445
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.9.163
      - KERNEL_VERSION=4.9.163-0409163
      - KERNEL_VERSION_C=201903131846
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.14.106
      - KERNEL_VERSION=4.14.106-0414106
      - KERNEL_VERSION_C=201903131950
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=disco
      - REPOSITORY=v4.19.29
      - KERNEL_VERSION=4.19.29-041929
      - KERNEL_VERSION_C=201903132331
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=disco
      - REPOSITORY=v4.20.16
      - KERNEL_VERSION=4.20.16-042016
      - KERNEL_VERSION_C=201903132232
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=disco
      - REPOSITORY=v5.0
      - KERNEL_VERSION=5.0.0-050000
      - KERNEL_VERSION_C=201903032031
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=disco
      - REPOSITORY=v5.0.2
      - KERNEL_VERSION=5.0.2-050002
      - KERNEL_VERSION_C=201903131832
      - UNSIGNED_IMG=1
      - NEED_MODULES=1

before_install:
  - docker pull ubuntu:${SYSTEM_VERSION}
  - docker ps -a
  - docker run --privileged -it -d -v ${PWD}:/sources -w /sources --name ubuntu ubuntu:${SYSTEM_VERSION} /bin/sh
  - export EXEC="docker exec ubuntu"
  - export SYSTEM_ARCH=amd64

install:
  - chmod +x ports/ci/travis/install_deps.sh
  - ports/ci/travis/install_deps.sh

script:
  - chmod +x ports/ci/travis/build.sh
  - ports/ci/travis/build.sh

#after_success:
#  - chmod +x ports/ci/travis/deploy.sh
#  - ports/ci/travis/deploy.sh

branches:
  only:
    - master

notifications:
  recipients:
    - hipersayan.x@gmail.com
  email:
    on_success: change
    on_failure: change
