language: cpp

matrix:
  include:
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v3.16.57
      - KERNEL_VERSION=3.16.57-031657
      - KERNEL_VERSION_C=201806170831
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v3.18.119
      - KERNEL_VERSION=3.18.119-0318119
      - KERNEL_VERSION_C=201808171540
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v4.4.151
      - KERNEL_VERSION=4.4.151-0404151
      - KERNEL_VERSION_C=201808220242
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.9.123
      - KERNEL_VERSION=4.9.123-0409123
      - KERNEL_VERSION_C=201808220630
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.14.66
      - KERNEL_VERSION=4.14.66-041466
      - KERNEL_VERSION_C=201808220733
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=cosmic
      - REPOSITORY=v4.17.18
      - KERNEL_VERSION=4.17.18-041718
      - KERNEL_VERSION_C=201808220323
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=cosmic
      - REPOSITORY=v4.18.4
      - KERNEL_VERSION=4.18.4-041804
      - KERNEL_VERSION_C=201808220230
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
      - export USE_QEMU=1

before_install:
  - docker pull ubuntu:${SYSTEM_VERSION}
  - docker ps -a
  - docker run --privileged -it -d -v ${PWD}:/sources -w /sources --name ubuntu ubuntu:${SYSTEM_VERSION} /bin/sh
  - export EXEC="docker exec ubuntu"
  - export SYSTEM_ARCH=amd64

install:
  - chmod +x ports/ci/travis/install_deps.sh
  - ports/ci/travis/install_deps.sh

script:
  - chmod +x ports/ci/travis/build.sh
  - ports/ci/travis/build.sh

#after_success:
#  - chmod +x ports/ci/travis/deploy.sh
#  - ports/ci/travis/deploy.sh

branches:
  only:
    - master

notifications:
  recipients:
    - hipersayan.x@gmail.com
  email:
    on_success: change
    on_failure: change
